[profile.default]
src = "contracts"
out = "out"
libs = ["forge-lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@openzeppelin/contracts/=forge-lib/openzeppelin-contracts/contracts/",
]
